apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-test-credentials
  namespace: cnpg-test
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pg-test-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: cnpg/pg-test
      property: username
  - secretKey: password
    remoteRef:
      key: cnpg/pg-test
      property: password
