apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-credentials
  namespace: {{ .Values.cluster.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.credentials.username }}
  password: {{ .Values.credentials.password }}

